version: 0.2

phases:
  pre_build:
    commands:
      # Install dependencies for server-side code
      - npm install
      # Install dependencies for client-side code
      - cd client && npm install
  build:
    commands:
      # Build client-side code
      - cd client && npm run build
artifacts:
  type: zip
  files:
    - '**/*'
  name: trackit-project-build
  discard-paths: yes
  location: codepipeline-us-west-2-983117758355
  
