version: 0.2

phases:
  pre_build:
    commands:
      # Install dependencies for server-side code
      - npm install
      # Install dependencies for client-side code
      - cd client && npm install 
  build:
    commands:
      # Build client-side code
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://codepipeline-us-west-2-983117758355/Trackit/

artifacts:
  files:
    - '**/*'
  base-directory: ./client/build
  
